import Head from 'next/head'
import axios from 'axios'
import Accordion from '@material-ui/core/Accordion'
import AccordionSummary from '@material-ui/core/AccordionSummary'
import AccordionDetails from '@material-ui/core/AccordionDetails'
import Container from '@material-ui/core/Container'
import Typography from '@material-ui/core/Typography'
import ExpandMoreIcon from '@material-ui/icons/ExpandMore'
import Link from '@material-ui/core/Link'
import React, { useEffect, useState } from 'react'
import { makeStyles, Theme, createStyles } from '@material-ui/core/styles'

const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    main: {
      width: '100%',
      flex: 1,
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
    },
    title: {
      marginTop: theme.spacing(8),
      marginBottom: theme.spacing(8),
    },
    heading: {
      fontSize: theme.typography.pxToRem(14),
      fontWeight: theme.typography.fontWeightRegular,
    },
    linkText: {
      marginLeft: theme.spacing(0.5),
      marginRight: theme.spacing(0.5),
    },
  })
)

const Faqs: React.FunctionComponent = () => {
  const styles = useStyles()
  const [contents, setContents] = useState([])

  useEffect(() => {
    axios.get('/api/faqs').then((response) => {
      const { data } = response
      setContents(data)
    })
  }, [])
  return (
    <div>
      <Head>
        <title>FAQs - Cleaning With Cooley</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container>
          <Typography
            className={styles.title}
            align="center"
            variant="h4"
            component="h1"
          >
            Frequently Asked Questions
          </Typography>

          <Accordion>
            <AccordionSummary
              expandIcon={<ExpandMoreIcon />}
              aria-controls="panel-content"
            >
              <Typography className={styles.heading}>
                What’s all included in your cleaning services?
              </Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography>
                We will clean every room for you, for more details please check
                out
                <Link className={styles.linkText}>What Is Included</Link>
              </Typography>
            </AccordionDetails>
          </Accordion>

          {contents.map((row, idx) => {
            return (
              <Accordion key={idx}>
                <AccordionSummary
                  expandIcon={<ExpandMoreIcon />}
                  aria-controls={`panel${idx}-content`}
                  id={`panel${idx}-header`}
                >
                  <Typography className={styles.heading}>
                    {row.title}
                  </Typography>
                </AccordionSummary>
                <AccordionDetails>
                  <Typography>{row.text}</Typography>
                </AccordionDetails>
              </Accordion>
            )
          })}
        </Container>
      </main>
    </div>
  )
}

export default Faqs
