import Head from 'next/head'
import Grid from '@material-ui/core/Grid'
import Container from '@material-ui/core/Container'
import Typography from '@material-ui/core/Typography'
import Card from '@material-ui/core/Card'
import CardContent from '@material-ui/core/CardContent'
import Image from 'next/image'
import imagesrc from '../public/testimage.jpg'
import { makeStyles, Theme, createStyles } from '@material-ui/core/styles'

const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    main: {
      width: '100%',
      flex: 1,
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
    },
    title: {
      marginTop: theme.spacing(4),
      marginBottom: theme.spacing(4),
      paddingLeft: theme.spacing(4),
      paddingRight: theme.spacing(4),
    },
    row: {
      marginTop: theme.spacing(1),
      marginBottom: theme.spacing(1),
      paddingLeft: theme.spacing(4),
      paddingRight: theme.spacing(4),
    },
    cardRoot: {
      display: 'flex',
    },
    cardDetails: {},
    cardContent: {
      marginLeft: theme.spacing(4),
    },
    cardImage: {
      objectFit: 'cover',
    },
    cardTitle: {
      marginBottom: theme.spacing(1),
    },
  })
)

export default function Included() {
  const styles = useStyles()
  return (
    <div>
      <Head>
        <title>Service Details - Cleaning With Cooley</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container>
          <Grid container>
            <Grid className={styles.title} item xs={12}>
              <Typography align="center" variant="h4" component="h1">
                Service Details
              </Typography>
            </Grid>

            <Grid className={styles.row} item xs={12}>
              <Card className={styles.cardRoot}>
                <Image
                  className={styles.cardImage}
                  src={imagesrc}
                  width={200}
                  height={200}
                  alt="Image Title"
                />
                <div className={styles.cardDetails}>
                  <CardContent className={styles.cardContent}>
                    <Typography
                      className={styles.cardTitle}
                      component="h5"
                      variant="h5"
                    >
                      Bedrooms &amp; Living Room
                    </Typography>
                    <Typography color="textSecondary">
                      General tidying up, mirrors cleaned, make bed (change
                      linen by request). Dust all accessible surfaces also wipe
                      and clean window sills.
                    </Typography>
                  </CardContent>
                </div>
              </Card>
            </Grid>

            <Grid className={styles.row} item xs={12}>
              <Card className={styles.cardRoot}>
                <Image
                  className={styles.cardImage}
                  src={imagesrc}
                  width={200}
                  height={200}
                  alt="Image Title"
                />
                <div className={styles.cardDetails}>
                  <CardContent className={styles.cardContent}>
                    <Typography
                      className={styles.cardTitle}
                      component="h5"
                      variant="h5"
                    >
                      Bedrooms &amp; Living Room
                    </Typography>
                    <Typography color="textSecondary">
                      General tidying up, mirrors cleaned, make bed (change
                      linen by request). Dust all accessible surfaces also wipe
                      and clean window sills.
                    </Typography>
                  </CardContent>
                </div>
              </Card>
            </Grid>

            <Grid className={styles.row} item xs={12}>
              <Card className={styles.cardRoot}>
                <Image
                  className={styles.cardImage}
                  src={imagesrc}
                  width={200}
                  height={200}
                  alt="Image Title"
                />
                <div className={styles.cardDetails}>
                  <CardContent className={styles.cardContent}>
                    <Typography
                      className={styles.cardTitle}
                      component="h5"
                      variant="h5"
                    >
                      Bedrooms &amp; Living Room
                    </Typography>
                    <Typography color="textSecondary">
                      General tidying up, mirrors cleaned, make bed (change
                      linen by request). Dust all accessible surfaces also wipe
                      and clean window sills.
                    </Typography>
                  </CardContent>
                </div>
              </Card>
            </Grid>

            <Grid className={styles.row} item xs={12}>
              <Card className={styles.cardRoot}>
                <Image
                  className={styles.cardImage}
                  src={imagesrc}
                  width={200}
                  height={200}
                  alt="Image Title"
                />
                <div className={styles.cardDetails}>
                  <CardContent className={styles.cardContent}>
                    <Typography
                      className={styles.cardTitle}
                      component="h5"
                      variant="h5"
                    >
                      Bedrooms &amp; Living Room
                    </Typography>
                    <Typography color="textSecondary">
                      General tidying up, mirrors cleaned, make bed (change
                      linen by request). Dust all accessible surfaces also wipe
                      and clean window sills.
                    </Typography>
                  </CardContent>
                </div>
              </Card>
            </Grid>
          </Grid>
        </Container>
      </main>
    </div>
  )
}
