import Head from 'next/head'
import Grid from '@material-ui/core/Grid'
import Container from '@material-ui/core/Container'
import Typography from '@material-ui/core/Typography'
import Card from '@material-ui/core/Card'
import CardContent from '@material-ui/core/CardContent'
import Image from 'next/image'
import { makeStyles, Theme, createStyles } from '@material-ui/core/styles'
import axios from 'axios'
import React, { useEffect, useState } from 'react'

const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    main: {
      width: '100%',
      flex: 1,
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
    },
    title: {
      marginTop: theme.spacing(4),
      marginBottom: theme.spacing(4),
      paddingLeft: theme.spacing(4),
      paddingRight: theme.spacing(4),
    },
    row: {
      marginTop: theme.spacing(1),
      marginBottom: theme.spacing(1),
      paddingLeft: theme.spacing(4),
      paddingRight: theme.spacing(4),
    },
    cardRoot: {
      display: 'flex',
      justifyContent: 'center',
      height: 200,
    },
    imageContainer: {
      height: 200,
      width: 200,
    },
    cardDetails: {
      width: '100%',
      marginTop: theme.spacing(2),
      marginBottom: theme.spacing(2),
    },
    cardContent: {
      marginLeft: theme.spacing(4),
    },
    cardImage: {
      objectFit: 'cover',
    },
    cardTitle: {
      marginBottom: theme.spacing(1),
    },
  })
)

const Included: React.FunctionComponent = () => {
  const [contents, setContents] = useState([])
  useEffect(() => {
    axios.get('/api/details').then((response) => {
      const { data } = response
      setContents(data)
    })
  }, [])
  const styles = useStyles()

  const rows = contents.map((row) => {
    const { key, img, imgTitle, title, description } = row
    return (
      <Grid key={key} className={styles.row} item xs={12}>
        <Card className={styles.cardRoot}>
          <div className={styles.imageContainer}>
            <Image
              layout="fixed"
              className={styles.cardImage}
              src={img}
              width={200}
              height={200}
              alt={imgTitle}
            />
          </div>
          <div className={styles.cardDetails}>
            <CardContent className={styles.cardContent}>
              <Typography
                className={styles.cardTitle}
                component="h5"
                variant="h5"
              >
                {title}
              </Typography>
              <Typography color="textSecondary">{description}</Typography>
            </CardContent>
          </div>
        </Card>
      </Grid>
    )
  })
  return (
    <div>
      <Head>
        <title>Service Details - Cleaning With Cooley</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container>
          <Grid container>
            <Grid className={styles.title} item xs={12}>
              <Typography align="center" variant="h4" component="h1">
                Service Details
              </Typography>
            </Grid>

            {rows}
          </Grid>
        </Container>
      </main>
    </div>
  )
}

export default Included
