import Head from 'next/head'
import Grid from '@material-ui/core/Grid'
import Container from '@material-ui/core/Container'
import Typography from '@material-ui/core/Typography'
import Card from '@material-ui/core/Card'
import CardContent from '@material-ui/core/CardContent'
import Image from 'next/image'
import { makeStyles, Theme, createStyles } from '@material-ui/core/styles'
import React from 'react'
import LivingRoomImage from '../public/images/livingroom.jpg'
import BathroomImage from '../public/images/bathroom.jpg'
import KitchenImage from '../public/images/kitchen.jpg'
import RoomImage from '../public/images/everyroom.jpg'

const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    main: {
      width: '100%',
      flex: 1,
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      paddingBottom: theme.spacing(4),
    },
    title: {
      marginTop: theme.spacing(4),
      marginBottom: theme.spacing(4),
      paddingLeft: theme.spacing(4),
      paddingRight: theme.spacing(4),
    },
    row: {
      marginTop: theme.spacing(1),
      marginBottom: theme.spacing(1),
      paddingLeft: theme.spacing(4),
      paddingRight: theme.spacing(4),
    },
    cardRoot: {
      display: 'flex',
      justifyContent: 'center',
      minHeight: 200,
    },
    imageContainer: {
      minHeight: 200,
      minWidth: 200,
      maxWidth: '30%',
      display: 'flex',
      alignItems: 'center',
    },
    cardDetails: {
      width: '100%',
      marginTop: theme.spacing(2),
      marginBottom: theme.spacing(2),
    },
    cardContent: {
      marginLeft: theme.spacing(4),
    },
    cardImage: {
      objectFit: 'cover',
      borderRadius: 8,
    },
    cardTitle: {
      marginBottom: theme.spacing(1),
    },
  })
)

const DetailsContent = [
  {
    key: 'bedroom',
    img: LivingRoomImage,
    imgTitle: 'Living Room Image',
    title: 'Bedrooms & Living Room',
    description:
      'General tidying up, mirrors cleaned, make bed (change linen by request). Dust all accessible surfaces also wipe and clean window sills.',
  },
  {
    key: 'bathroom',
    img: BathroomImage,
    imgTitle: 'Bathroom Image',
    title: 'Bathrooms',
    description:
      'Shower/bathtub and tile wall scrubbed clean and disinfected. Toilet scrubbed clean and disinfected including base and behind toilet. Vanity and sink scrubbed clean and disinfected, mirrors cleaned, fixtures cleaned and shined.',
  },
  {
    key: 'kitchen',
    img: KitchenImage,
    imgTitle: 'Kitchen Image',
    title: 'Kitchens',
    description:
      'Clean the stovetop and backsplash. Clean and sanitize interior and exterior of microwave. Clean the exterior of appliances, clean and disinfect the sink. Hand-wash and disinfect counters, wipe down table and chairs. Cabinets wiped down. Hand-wipe outside of the trash can.',
  },
  {
    key: 'room',
    img: RoomImage,
    imgTitle: 'Room Image',
    title: 'Every Room',
    description:
      'General tidying up, clean all floor surfaces (vacuum & mop). Dust exposed baseboards and remove smudges from light switch plates. Clean window sills and remove trash and recycling.',
  },
]

const Included: React.FunctionComponent = () => {
  const contents = DetailsContent
  const styles = useStyles()

  const rows = contents.map((row) => {
    const { key, img, imgTitle, title, description } = row
    return (
      <Grid key={key} className={styles.row} item xs={12}>
        <Card className={styles.cardRoot}>
          <div className={styles.imageContainer}>
            <Image
              layout="intrinsic"
              objectFit="cover"
              className={styles.cardImage}
              src={img}
              alt={imgTitle}
            />
          </div>
          <div className={styles.cardDetails}>
            <CardContent className={styles.cardContent}>
              <Typography
                className={styles.cardTitle}
                component="h5"
                variant="h5"
              >
                {title}
              </Typography>
              <Typography color="textSecondary">{description}</Typography>
            </CardContent>
          </div>
        </Card>
      </Grid>
    )
  })
  return (
    <div>
      <Head>
        <title>Service Details - Cleaning With Cooley</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container>
          <Grid container>
            <Grid className={styles.title} item xs={12}>
              <Typography align="center" variant="h4" component="h1">
                Service Details
              </Typography>
            </Grid>
            {rows}
          </Grid>
        </Container>
      </main>
    </div>
  )
}

export default Included
