import Head from 'next/head'
import Grid from '@material-ui/core/Grid'
import Container from '@material-ui/core/Container'
import Button from '@material-ui/core/Button'
import Typography from '@material-ui/core/Typography'
import React from 'react'
import Carousel from '../components/Carousel'
import HomeCard from '../components/HomeCard'
import { makeStyles, Theme, createStyles } from '@material-ui/core/styles'
import Link from 'next/link'
import Image from 'next/image'
import BondedImage from '../public/images/bonded.png'
import CarouselImage1 from '../public/images/carousel_1.jpg'
import CarouselImage2 from '../public/images/carousel_2.jpg'
import CarouselImage3 from '../public/images/carousel_3.jpg'
import CarouselImage4 from '../public/images/carousel_4.jpg'

const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    container: {
      minHeight: '100vh',
    },
    main: {
      width: '100%',
      flex: 1,
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
    },
    slide: {
      height: 600,
      width: '100%',
      overflow: 'hidden',
      display: 'block',
      position: 'relative',
    },
    row: {
      marginBottom: theme.spacing(8),
    },
    imageRow: {
      marginBottom: theme.spacing(4),
      display: 'flex',
      alignItems: 'center',
    },
    largeButton: {
      color: 'white',
      padding: `${theme.spacing(2)}px ${theme.spacing(4)}px`,
      marginTop: theme.spacing(2),
      marginLeft: theme.spacing(2),
      marginRight: theme.spacing(2),
    },
    title: {
      fontWeight: 'bold',
      marginBottom: theme.spacing(2),
    },
    contactRow: {
      marginTop: theme.spacing(12),
      marginBottom: theme.spacing(12),
    },
    badgeImage: {
      width: 150,
      height: 150,
      cursor: 'pointer',
      marginLeft: theme.spacing(2),
      marginRight: theme.spacing(2),
    },
    sealImage: {
      width: 200,
      height: 42,
      cursor: 'pointer',
      marginLeft: theme.spacing(2),
      marginRight: theme.spacing(2),
    },
    bondedImage: {
      width: 150,
      height: 150,
      marginLeft: theme.spacing(2),
      marginRight: theme.spacing(2),
    },
  })
)

const PHONE_NUMBER = '312-820-4947'
const CarouselImages = [
  CarouselImage1,
  CarouselImage2,
  CarouselImage3,
  CarouselImage4,
]

const Home: React.FunctionComponent = () => {
  const styles = useStyles()
  return (
    <div className={styles.container}>
      <Head>
        <title>Home - Cleaning With Cooley</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Carousel>
          {CarouselImages.map((img, idx) => {
            return (
              <div key={idx} className={styles.slide}>
                <Image
                  src={img}
                  alt={`carousel-image-${idx}`}
                  objectFit="cover"
                  layout="fill"
                  // width="100%"
                  // height={600}
                  loading="eager"
                />
              </div>
            )
          })}
        </Carousel>
        <Container maxWidth="xl">
          <Grid container>
            <Grid
              className={`${styles.row} ${styles.contactRow}`}
              justifyContent="center"
              container
              item
              xs={12}
            >
              <Link href={`tel:${PHONE_NUMBER}`}>
                <Button
                  className={styles.largeButton}
                  variant="contained"
                  size="large"
                  color="primary"
                >
                  <Typography variant="h6">
                    Contact Us For A Free Quote
                  </Typography>
                </Button>
              </Link>
            </Grid>

            <Grid className={styles.row} container item xs={12}>
              <Grid container item xs={12} justifyContent="center">
                <Typography
                  className={styles.title}
                  align="center"
                  variant="h5"
                  component="h2"
                >
                  What is Cleaning With Cooley
                </Typography>
              </Grid>

              <Grid container item xs={12} justifyContent="center">
                <HomeCard title="Who We Are" icon="fas fa-user-tie">
                  Cleaning with Cooley is a Chicago Cleaning Service located in
                  the downtown Chicago area. We offer a wide range of services
                  to residential clients and business owners, from general house
                  cleaning, office cleaning and much more!
                </HomeCard>

                <HomeCard title="Our Mission" icon="fas fa-bullseye">
                  Our goal is to provide a clean and a positive atmosphere in
                  our clients’ home by delivering world class customer service
                  and cleaning. We value open and honest relationships with our
                  clients and love giving them a little time back in their week
                  to focus on their goals. We want to always deliver the “Wow”
                  through our services.
                </HomeCard>

                <HomeCard title="What We Do" icon="fas fa-hand-sparkles">
                  We tailored our residential and commercial cleaning service to
                  make sure every space - whether it’s a studio apartment in
                  Wicker Park, a brownstone in Lincoln Park, or an office in The
                  Loop - is as beautiful as it can be with complete
                  satisfaction!
                </HomeCard>
              </Grid>
            </Grid>

            <Grid className={styles.row} container item xs={12}>
              <Grid container justifyContent="center">
                <Typography
                  className={styles.title}
                  align="center"
                  variant="h5"
                  component="h2"
                >
                  Why Clean With Cooley
                </Typography>
              </Grid>

              <Grid container justifyContent="center">
                <HomeCard title="Eco Friendly" icon="fas fa-leaf">
                  We offer Eco-friendly house cleaning products that don’t
                  contain harsh nor harmful chemicals. We always want to help
                  you maintain a clean &amp; healthy home.
                </HomeCard>

                <HomeCard
                  title={'Licensed, Insured & Bonded'}
                  icon="fas fa-shield-alt"
                >
                  Cleaning with Cooley is fully Licensed, Bonded &amp; Insured
                  to protect your home and give you a piece of mind.
                </HomeCard>
              </Grid>

              <Grid container justifyContent="center">
                <HomeCard title="Great Customer Service" icon="fas fa-smile">
                  Our #1 goal is to deliver world class customers service to our
                  clients. We provide exceptional training to all our
                  professional housekeepers/cleaners. All our employees undergo
                  a back ground check because we value open and honest
                  relationships with our clients. We always want to provide a
                  clean and positive atmosphere in our clients’ home!
                </HomeCard>

                <HomeCard
                  title="100% Satisfaction Guarantee"
                  icon="fas fa-thumbs-up"
                >
                  It’s rare to find a company that stands behind its work. If
                  for any reason you’re not satisfied with our work let us know
                  within 48 hours and we will return to re-clean any of the
                  areas missed free of charge! Our goal is to always put you and
                  your home first.
                </HomeCard>
              </Grid>
            </Grid>

            <Grid
              className={styles.row}
              container
              justifyContent="center"
              item
              xs={12}
            >
              <Link href="/services">
                <Button
                  className={styles.largeButton}
                  variant="contained"
                  size="large"
                  color="primary"
                >
                  <Typography variant="h6">Check Out Our Services</Typography>
                </Button>
              </Link>
              <Link href={`tel:${PHONE_NUMBER}`}>
                <Button
                  className={styles.largeButton}
                  variant="contained"
                  size="large"
                  color="primary"
                >
                  <Typography variant="h6">
                    Contact Us For A Free Quote
                  </Typography>
                </Button>
              </Link>
            </Grid>

            <Grid
              className={styles.imageRow}
              container
              justifyContent="center"
              item
              xs={12}
            >
              <Link href="https://www.chamberofcommerce.com/united-states/illinois/chicago/house-cleaning-service/2012861231-cleaning-with-cooley?source=memberwebsite">
                <div className={styles.badgeImage}>
                  <img
                    src="https://coc.codes/images/badge/2012861231"
                    alt="COCBadge"
                  />
                </div>
              </Link>
              <div className={styles.bondedImage}>
                <Image src={BondedImage} alt="Liscenced and Bonded" />
              </div>
              <Link href="https://www.bbb.org/us/il/chicago/profile/cleaning-services/cleaning-with-cooley-llc-0654-1000028192/#sealclick">
                <div className={styles.sealImage}>
                  <img
                    src="https://seal-chicago.bbb.org/seals/blue-seal-200-42-bbb-1000028192.png"
                    alt="Cleaning With Cooley, LLC BBB Business Review"
                  />
                </div>
              </Link>
            </Grid>
          </Grid>
        </Container>
      </main>
    </div>
  )
}

export default Home
