import Head from 'next/head'
import React, { useState } from 'react'
import Grid from '@material-ui/core/Grid'
import Container from '@material-ui/core/Container'
import Tabs from '@material-ui/core/Tabs'
import Tab from '@material-ui/core/Tab'
import Typography from '@material-ui/core/Typography'
import { makeStyles, Theme, createStyles } from '@material-ui/core/styles'
import ServiceCard from '../components/ServiceCard'

const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    main: {
      width: '100%',
      flex: 1,
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      paddingTop: theme.spacing(1),
    },
    row: {
      marginBottom: theme.spacing(8),
    },
    card: {
      margin: theme.spacing(1),
      paddingTop: theme.spacing(3),
      paddingBottom: theme.spacing(3),
    },
  })
)

const mapElement = (service) => {
  const { key, title, subtitle } = service
  return (
    <Grid key={key} xs={12} md={6} item>
      <ServiceCard>
        <Typography variant="h6">{title}</Typography>
        {subtitle && <Typography variant="subtitle1">{subtitle}</Typography>}
      </ServiceCard>
    </Grid>
  )
}

const ServicesConstant = {
  services: [
    {
      key: 'one-bed',
      title: 'Studio/One Bedroom',
      subtitle: '',
    },
    {
      key: 'two-bed',
      title: 'Two Bedroom',
      subtitle: '',
    },
    {
      key: 'three-bed',
      title: 'Three Bedroom',
      subtitle: '',
    },
    {
      key: 'house',
      title: 'House Clean',
      subtitle: '',
    },
    {
      key: 'commercial',
      title: 'Commercial Clean',
      subtitle: '',
    },
    {
      key: 'event',
      title: 'Special Event Clean',
      subtitle: '',
    },
    {
      key: 'airbnb',
      title: 'Airbnb Turnover Clean',
      subtitle: '',
    },
    {
      key: 'condo',
      title: 'Condo Association Clean',
      subtitle: '',
    },
    {
      key: 'move',
      title: 'Move In/Out Clean',
      subtitle: '',
    },
    {
      key: 'room',
      title: 'Individual Room Clean',
      subtitle: '',
    },
    {
      key: 'salon',
      title: 'Beauty/Barber Shops',
      subtitle: '',
    },
  ],
  addons: [
    {
      key: 'window',
      title: 'Interior Window Clean',
      subtitle: '',
    },
    {
      key: 'fridge',
      title: 'Interior Refrigerator Clean',
      subtitle: '',
    },
    {
      key: 'oven',
      title: 'Interior Oven Clean',
      subtitle: '',
    },
    {
      key: 'laundry',
      title: 'Laundry - Wash, Dry & Fold',
      subtitle: '',
    },
    {
      key: 'closet',
      title: 'General Closet Organization',
      subtitle: '',
    },
    {
      key: 'cabinet',
      title: 'General Kitchen Organization',
      subtitle: '',
    },
  ],
}

// const createSkeleton = (val, idx) => {
//   return (
//     <Grid key={idx} xs={12} md={6} item>
//       <ServiceCard>

//       </ServiceCard>
//     </Grid>
//   )
// }

const Services: React.FunctionComponent = () => {
  const styles = useStyles()
  const [tabValue, setTabValue] = useState(0)

  const { services = [], addons = [] } = ServicesConstant
  const servicesElements = services.map(mapElement)
  const addonsElements = addons.map(mapElement)

  const tabContents = tabValue === 0 ? servicesElements : addonsElements

  const handleChange = (e, value) => {
    setTabValue(value)
  }
  return (
    <div>
      <Head>
        <title>Services - Cleaning With Cooley</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container>
          <Grid container>
            <Grid className={styles.row} item xs={12}>
              <Tabs
                value={tabValue}
                onChange={handleChange}
                indicatorColor="primary"
                textColor="primary"
                variant="fullWidth"
                centered
              >
                <Tab label="Services" />
                <Tab label="Add-ons" />
              </Tabs>
            </Grid>

            <Grid
              className={styles.row}
              container
              item
              justifyContent="center"
              xs={12}
            >
              {tabContents}
            </Grid>
          </Grid>
        </Container>
      </main>
    </div>
  )
}

export default Services
