import Head from 'next/head'
import { useState } from 'react'
import Grid from '@material-ui/core/Grid'
import Container from '@material-ui/core/Container'
import Tabs from '@material-ui/core/Tabs'
import Tab from '@material-ui/core/Tab'
import Typography from '@material-ui/core/Typography'
import { makeStyles, Theme, createStyles } from '@material-ui/core/styles'
import ServiceCard from '../components/ServiceCard'

const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    main: {
      width: '100%',
      flex: 1,
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      paddingTop: theme.spacing(1),
    },
    row: {
      marginBottom: theme.spacing(8),
    },
    card: {
      margin: theme.spacing(1),
      paddingTop: theme.spacing(3),
      paddingBottom: theme.spacing(3),
    },
  })
)

export default function Services() {
  const styles = useStyles()
  const [tabValue, setTabValue] = useState(0)

  const handleChange = (e, value) => {
    setTabValue(value)
  }
  return (
    <div>
      <Head>
        <title>Services - Cleaning With Cooley</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container>
          <Grid container>
            <Grid className={styles.row} item xs={12}>
              <Tabs
                value={tabValue}
                onChange={handleChange}
                indicatorColor="primary"
                textColor="primary"
                variant="fullWidth"
                centered
              >
                <Tab label="Services" />
                <Tab label="Add-ons" />
              </Tabs>
            </Grid>

            <Grid
              className={styles.row}
              container
              item
              justifyContent="center"
              xs={12}
            >
              <Grid xs={12} md={6} item>
                <ServiceCard>
                  <Typography>Studio/One Bedroom</Typography>
                </ServiceCard>
              </Grid>
              <Grid xs={12} md={6} item>
                <ServiceCard>
                  <Typography>Two Bedroom</Typography>
                </ServiceCard>
              </Grid>
            </Grid>
          </Grid>
        </Container>
      </main>
    </div>
  )
}
